### ISSUE TITLE
[FEATURE] Can you add a feature that makes no grave spawn when a player kills you?

### ISSUE THREAD

**Issue by Redny22** [ginsm/forgotten-graves#105]

**Comment by ginsm** [comment]
Hey, thank you for the suggestion! I'll definitely look into adding this at some point as a config option.

It might be a little though as I'm having issues with my hands that prevent me from coding.

**Comment by ginsm** [comment]
Ended up being an easier change, just a few lines of code, so it was manageable. I'm going to be releasing it to Modrinth and CurseForge shortly. I'll close this for now but let me know if you run into any issues, thanks!
