### ISSUE TITLE
[FEATURE] cosmetic armor support

### ISSUE THREAD

**Issue by kerrschtein** [ginsm/forgotten-graves#29]
hi!! i love this mod, the ambiance and utility it provides is wonderful! would it be possible to add support for this mod: https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-fabric

**Comment by ginsm** [comment]
Howdy!

Cosmetic Armor Fabric seems to utilize the Trinkets API which I'm planning on adding support for very soon -- probably in the next day or two.

**Comment by ginsm** [comment]
Commit 071baf2 should resolve this issue:

> This release resolve issue #29 by adding Trinkets API support.

If you run into any issues please let me know, thanks! :)
