### ISSUE TITLE
Server crash and dup glitch

### ISSUE THREAD

**Issue by Aimez238** [ginsm/forgotten-graves#34]
I run a server with a few of my friends and the latest set up updates has broken something with this mod. If we go to grab our stuff, it crashes the server, and when we come back online, it will have given all of our stuff again, even if we already have it.

**Comment by ginsm** [comment]
Hey there, sorry to hear about that. I'll need some more information in order to help, can you please fill this out?

```
**Minecraft Version:**

**Forgotten Graves Version:** 

**Crash Log:**

**Additional Context:**
```

If you could use a service like https://pastebin.com for the crash log it'd be appreciated, thanks! :)

**Comment by afloofflam** [comment]
I had the same issue today...not sure if you need all of this detail, but here's my crashlog:

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2/5/22, 4:03 PM
Description: Exception in server tick loop

java.lang.IncompatibleClassChangeError: Method 'boolean dev.emi.trinkets.TrinketSlot.canInsert(net.minecraft.class_1799, dev.emi.trinkets.api.SlotReference, net.minecraft.class_1309)' must be InterfaceMethodref constant
	at me.mgin.graves.compat.TrinketsCompat.equipItem(TrinketsCompat.java:108)
	at me.mgin.graves.compat.TrinketsCompat.setInventory(TrinketsCompat.java:49)
	at me.mgin.graves.block.GraveBase.useGrave(GraveBase.java:246)
	at me.mgin.graves.block.GraveBase.method_9576(GraveBase.java:124)
	at net.minecraft.class_3225.method_14266(class_3225.java:247)
	at net.minecraft.class_3225.method_21717(class_3225.java:221)
	at net.minecraft.class_3225.method_14263(class_3225.java:196)
	at net.minecraft.class_3244.method_12066(class_3244.java:1019)
	at net.minecraft.class_2846.method_12361(class_2846.java:34)
	at net.minecraft.class_2846.method_11054(class_2846.java:8)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:151)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:780)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:162)
	at net.minecraft.class_1255.method_16075(class_1255.java:125)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:762)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756)
	at net.minecraft.class_1255.method_18857(class_1255.java:134)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:741)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2340396544 bytes (2231 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
	Identifier: Intel64 Family 6 Model 140 Stepping 1
	Microarchitecture: Tiger Lake
	Frequency (GHz): 2.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9a49
	Graphics card #0 versionInfo: DriverVersion=30.0.100.9864
	Graphics card #1 name: NVIDIA GeForce MX450
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x1f97
	Graphics card #1 versionInfo: DriverVersion=30.0.14.7180
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 28479.20
	Virtual memory used (MB): 25417.56
	Swap memory total (MB): 12547.95
	Swap memory used (MB): 1878.33
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		advancednetherite: Advanced Netherite 1.4.0-1.18.1
		amecsapi: Amecs API 1.3.3+mc1.18-pre1
		appleskin: AppleSkin 2.3.0+mc1.18.1
		architectury: Architectury 3.6.16
		attributefix: AttributeFix 13.0.5
		backslot: BackSlot 1.2.4
		backslotaddon: BackSlot Addon 1.0.7
		balm-fabric: Balm 2.4.1+0
		bclib: BCLib 1.3.0
		betteranimalsplus: Better Animals Plus 1.18.1-11.0.4
		betterend: Better End 1.0.2
		betternether: Better Nether 6.0.10
		campfire_torches_plus: Campfire Torches Plus 1.0.0
		cardinal-components-base: Cardinal Components API (base) 4.1.0
		cardinal-components-block: Cardinal Components API (blocks) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.1.0
		cardinal-components-item: Cardinal Components API (items) 4.0.1
		carrier: Carrier 1.9.1
		chalk: Chalk 1.2.1
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.1.48
		clumps: Clumps 8.0.0+5
		collective-fabric: Collective (Fabric) 4.1
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		comforts: Comforts 1.0.1-1.18.1
		companion: Companion 1.1.1
		companion_bats: Companion Bats 1.18.7
		controlling: Controlling For Fabric 9.0+14
		craftingtweaks: Crafting Tweaks 13.0.0
		dataattributes: Data Attributes 1.1.5
		doublejump: Double Jump Mod 1.0.1+mc1.18
		early_buckets: Early-Game Buckets 2.0.0+1.18
		easymagic: Easy Magic 3.2.1
		enchdesc: EnchantmentDescriptions 9.0.11
		fabric: Fabric API 0.46.4+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.8+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.6+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.6+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.11+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.4+d7c144a865
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.12+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.14+713c266865
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.8+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.8+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.9+d7c144a865
		fabricloader: Fabric Loader 0.12.12
		farmersdelight: Farmer's Delight 1.18.1-0.2.0
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 1.0.1+1.18.1
		fiber: fiber 0.23.0-2
		fixedanvilrepaircost-fabric: Fixed Anvil Repair Cost (Fabric) 1.6
		forgeconfigapiport: Forge Config API Port 3.1.1
		forgottengraves: Forgotten Graves v2.3.1-mc1.18.1
		forgottenrecipes: ForgottenRecipes 1.18.1-1.0.0
		furnacerecycle-fabric: Furnace Recycle (Fabric) 1.0
		geckolib3: Geckolib 3.0.32
		gimme_bundles: Gimme bundles! 1.0.4
		grassseeds-fabric: Grass Seeds (Fabric) 1.6
		guardvillagers: Guard Villagers Fabric 1.0.2
		healingcampfire-fabric: Healing Campfire (Fabric) 3.3
		hookshot: Hookshot 24.0
		icarus: Icarus 1.9
		inmis: Inmis 2.5.1-1.18.1
		iris: Iris 1.2.0-pre
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.1.0+1.17
		libcd: LibCapableData 3.0.3+1.16.3
		magna: Magna 1.7.0-1.18-pre1
		maybe-data: Maybe data 1.0.1-1.17
		medievalmusic: Medieval Music Mod 1.18-1.3
		megane: megane 7.1.0
		megane-api: megane-api 7.0.0
		megane-fabric-transfer: megane-fabric-transfer 7.0.0
		megane-runtime: megane-runtime 7.1.0
		megane-vanilla: megane-vanilla 7.0.0
		minecraft: Minecraft 1.18.1
		mobscarecrow: Mob Scarecrow 1.1.0
		modmenu: Mod Menu 3.0.1
		morevillagers-fabric: MoreVillagersFabric 3.1.1-SNAPSHOT
		mostructures: Mo' Structures 1.3.0-pre1+1.18
		mousetweaks: Mouse Tweaks 2.22
		mythic-mounts: Mythic Mounts 1.18-4.0
		naturescompass: Nature's Compass 1.18.1-2.0.2-fabric
		net_objecthunter_exp4j: exp4j 0.4.8
		no_null_processors: No Null Processors - Fabric 2.0.1+1.18.1
		nohostilesaroundcampfire-fabric: No Hostiles Around Campfire (Fabric) 3.8
		omega-config: OmegaConfig 1.2.3-1.18.1
		opc: Offline Player Cache 0.0.1
		orderly: Orderly 2.0.0-alpha.10+custom-1.18
		org_anarres_jcpp: jcpp 1.4.14
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		oxidized: Oxidized 1.5.2
		placeholder-api: Placeholder API 1.1.3+1.17.1
		playerex: PlayerEx 3.1.3
		polymorph: Polymorph 0.0.19-1.18.1
		pride: Pride Lib 1.1.0+1.17
		puzzleslib: Puzzles Lib 3.1.3
		recipeconditions: Fabric Recipe Conditions 0.4.1
		repurposed_structures: Repurposed Structures 3.3.7+1.18.1
		roughlyenoughitems: Roughly Enough Items 7.2.422
		seedfix: Seed Fix 1.0.0
		smallernetherportals-fabric: Smaller Nether Portals (Fabric) 1.8
		sodium: Sodium 0.4.0-alpha6+build.14
		spruceui: SpruceUI 3.3.0+1.17
		static-content: Static Content 1.0.2-1.16.2
		staticdata: Static Data 1.1.2
		teenycoal: Teeny Coal 1.1.0-1.16.x-1.17.x-1.18.x
		terralith: Terralith for Fabric 2.0.12
		toolstats: ToolStats 8.0.3
		totw_additions: Towers of the Wild: Additions 1.1.0
		towers_of_the_wild_reworked: Towers of the Wild: Reworked 2.1.1
		tradingpost: Trading Post 3.1.2
		trashslot: TrashSlot 11.0.1
		treeharvester-fabric: Tree Harvester (Fabric) 4.1
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.2.0
		vanilla-hammers: Vanilla Hammers 3.2.0-1.18.1
		vanillaexcavators: Vanilla Excavators 1.1.0
		vanillashears: Vanilla Shears 1.18.1-1.1.1
		vanillatweaks: VanillaTweaks 1.5.53
		visualworkbench: Visual Workbench 3.1.0
		walljump: Wall Jump 0.0.2
		waystones: Waystones 9.0.3
		wthit: wthit 4.5.1
		xaerominimap: Xaero's Minimap 22.1.2
		xaeroworldmap: Xaero's World Map 1.20.1
	Server Running: true
	Player Count: 1 / 8; [class_3222['rdrkx'/89, l='ServerLevel[whelp]', x=125.03, y=44.02, z=953.62]]
	Data Packs: vanilla, Fabric Mods, file/Gravel2Flint.zip (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'

**Comment by ginsm** [comment]
Thanks for the log, afloofflam. I'm going to start looking into that.

If you could still send your log, Aimez238, I'd appreciate it. I'd like to see if it's the same issue or something different :thinking:.

**Comment by ginsm** [comment]
OK, I just released `v2.4.1` on [here](https://github.com/ginsm/forgotten-graves/releases/tag/mc1.18.1-v2.4.1) and [CurseForge](https://www.curseforge.com/minecraft/mc-mods/forgotten-graves/files/3638424) which should resolve this issue. Can you both update and see if it has fixed the issue for you two? It'll need to be updated on both the server & the client.

**Comment by afloofflam** [comment]
No crash after a breaking the gravestone! Thank you for fixing this so fast.

**Comment by ginsm** [comment]
> No crash after a breaking the gravestone! Thank you for fixing this so fast.

Great, glad to hear it. You're welcome! :)

I'm gonna close this for now since it seems to be fixed. Feel free to reopen it Aimez238 if this didn't fix your issue, thanks!
