### ISSUE TITLE
[BUG] Client is crashing when trying to break gravestone

### ISSUE THREAD

**Issue by TheButterbrotMan** [ginsm/forgotten-graves#35]
**Describe the bug**
Client is crashing when breaking a gravestone

**Forgotten Graves Version**
2.3.1

**To Reproduce**
A list of steps to reproduce your issue, i.e.:
1. Install https://www.curseforge.com/minecraft/modpacks/deathdusk
2. Die
3. Try to break gravestone

**Additional context**
https://bytebin.lucko.me/jfuhSeuW2a

https://medal.tv/de/games/minecraft/clips/a9V34llOyRgs7/CXTmetm7jSfs?invite=cr-MSxGZlUsNDQyMDg1ODgs

**Comment by TheButterbrotMan** [comment]
https://github.com/TheButterbrotMan/Deathdusk/issues/10

**Comment by TheButterbrotMan** [comment]
Server is crashing also:
https://bytebin.lucko.me/JM50KTN3ne

**Comment by ginsm** [comment]
So this is most likely the same issue as #34. I'd recommend updating to Forgotten Graves 2.4.1 (released yesterday) which should resolve this.
