### ISSUE TITLE
[BUG] Crashing on Death

### ISSUE THREAD

**Issue by QzFulcrumX** [ginsm/forgotten-graves#37]
**Describe the bug**
Crashing on death

**Forgotten Graves Version**
forgottengraves-mc1.18.2-v2.5.0

**To Reproduce**
A list of steps to reproduce your issue, i.e.:
1. Spawned in a world (tried new and existing worlds, survival/creative)
2. Die using any method (falling, fire, /kill command)
3. See the Respawn/Title Screen buttons for a split second before crashing.
4. After relogging, all items and XP are lost.

**Expected behavior**
A grave will spawn on death location with items and XP inside.

**Additional context**
Crash Report: https://pastebin.com/4SCsYjFx
Debug Log: https://pastebin.com/SyaMAhgi
Modlist(w/o forgottengraves): https://pastebin.com/AvVYQKQ8

Downloaded the mod and its dependencies, did not tweak any setting and started a world in single player. Without the mod, dying is no issue and back to vanilla behavior (dropped items, max 7 levels, etc.)

**Comment by ginsm** [comment]
Hey, thanks for creating the issue. Are you using CurseForge? If so, could you [export](https://support.curseforge.com/en/support/solutions/articles/9000198501-exporting-and-importing-modpacks#Exporting-a-modpack) the profile that's having issues? 

I'd like to test with your current mod configuration to see what's going on and that'd save me a lot of time, thanks!

**Comment by QzFulcrumX** [comment]
I am unfortunately not, but I have edited in the mods I used as of this day, all of these are also downloaded today so it all will be their latest versions, except for inmis, which is from a comment chain from a guy who retextured the backpacks. [retextured link dropbox](https://www.dropbox.com/s/d0phpop10gia0gs/inmis_retexured-2.5.1-1.18.1.jar?dl=1)

**Comment by ginsm** [comment]
Hmm, so I downloaded the mods and tested it but I couldn't replicate it:

https://user-images.githubusercontent.com/52685959/156571276-0389695c-d330-4ccd-bc16-e0fb9852ef12.mp4

I tried `/kill`, falling, burning myself in lava, burning myself with a flint and steel, shooting myself with a bow, etc.. it all worked properly.

I went ahead and changed the implementation of the line of code your game is having issues with though. Can you try [this jar](https://1drv.ms/u/s!AoWqGTolezjmoo1xryfGJY7XWGl0-g?e=sEDcOg) instead and see if it resolves your issue?

If it does, please let me know so I can use that implementation moving forward! :)
