### ISSUE TITLE
[BUG] 'Backslot' item lost on death

### ISSUE THREAD

**Issue by NTKiddd** [ginsm/forgotten-graves#40]
**Describe the bug**
I'm running my game with **Forgotten Graves** and **Backslot** mod but it seems like the items in the 'backslot'  will lost whenever I die 

**Forgotten Graves Version**
v2.5.0

**To Reproduce**
A list of steps to reproduce your issue, i.e.:
1. Put any item into the 'backslot'
2. Die
3. Encounter error

**Expected behavior**
I don't really have any specific idea of how it should looks like but I want to just report in case it's possible

**Additional context**

**Screenshots**

**Comment by ginsm** [comment]
Hey there,

Currently this mod only has support for mods that add new slots via the [Trinkets API](https://www.curseforge.com/minecraft/mc-mods/trinkets-fabric). However, I'll look into adding support for BackSlot slots as well for the next update.

Thanks for the report! :)

**Comment by ginsm** [comment]
Released a 1.18.1 and 1.18.2 version that should fix this -- let me know if you have any other issues, thanks!
