### ISSUE TITLE
[BUG] Incompatibility with Inventorio Mod

### ISSUE THREAD

**Issue by ConqAra** [ginsm/forgotten-graves#42]
When I retrieve my gravestone, it doesn't give the tools in the tool slot back that's provided by inventorio. Can you add compatibility?

**Comment by ginsm** [comment]
Hey there, sorry for the delayed response!

I worked on adding compatibility for Inventorio tonight some and the functionality seems to be working.  I need to get some sleep now, and have work tomorrow, but I'll do some more extensive testing tomorrow night and see if I can't get it released then as well.

Thanks for the report!

**Comment by ginsm** [comment]
This should now be resolved in `v2.6.0` for `1.18.1` and `1.18.2` on CurseForge. 

If you run into any other issues let me know, thanks!
