### ISSUE TITLE
 [1.18.2] Collector's Album "Persist album through death option" is incompatible with Forgotten Graves

### ISSUE THREAD

**Issue by ConqAra** [ginsm/forgotten-graves#45]
Forgotten Graves doesn't spawn a grave if this option from [Collector's Album](https://www.curseforge.com/minecraft/mc-mods/collectors-album) is checked. Looks like it just causes Forgotten Graves to break and not work at all if Collector's Album forces an album to persist through death, even if you don't have an album in your inventory. [The mod developer said there was nothing he could do about that on his side.](https://github.com/Toma1O6/CollectorsAlbum/issues/10)

**Comment by ginsm** [comment]
Howdy! I'm currently working on updating the project to 1.19 but once I'm done with that I'll look into this and see if I can't fix the issue. If you'd like to help me get a head-start into looking into the issue, any logs associated with the issue would be appreciated. 

Happy holidays! :)

**Comment by ConqAra** [comment]
Didn't see anything that specific, but here's my log of me going into the world, having stuff in my inventory / on me and then dying. gravestone did not spawn!
[Log](https://paste.ee/p/Hwwti)

**Comment by ginsm** [comment]
I'm going to close this for now as Toma and I discussed this [here](https://github.com/Toma1O6/CollectorsAlbum/issues/10#issuecomment-1361100187). For now, I've added instructions on making the two addons compatible on the [CurseForge page](https://www.curseforge.com/minecraft/mc-mods/forgotten-graves).

Thanks for bringing this to our attention! 😄
