### ISSUE TITLE
[BUG] Graves bugged with Supplementaries' bombs

### ISSUE THREAD

**Issue by nbdTyler** [ginsm/forgotten-graves#60]
**Describe the bug**
When a player dies via bomb, the grave does not spawn as a regular "grave", allowing you to click or break it; instead it will drop as an item, and you cannot receive your items back from it.

**Forgotten Graves Version**
3.0.3

**To Reproduce**
1. Acquire a bomb from Supplementaries
2. Bomb yourself or a friend to death
3. Your/Their Grave will appear as a dropped item rather than a breakable grave

**Expected behavior**
After dying to a bomb, your grave will appear as normal, allowing you to collect your items from it

**Additional context**
Friend accidentally killed me with a bomb, and when I went back to retrieve my items, there was just a floating grave block

**Screenshots**

**Comment by nbdTyler** [comment]
Running 1.19.2, and I just tried that config change, and it works now, thanks a bunch!!

**Comment by ginsm** [comment]
Awesome, glad that resolved it for now. :)
