### ISSUE TITLE
[BUG] getting killed by creepers (and possibly explosions but i haven't tested this) will prevent graves spawning.

### ISSUE THREAD

**Issue by jabthetab** [ginsm/forgotten-graves#65]
**Describe the bug**
title is self-explanatory. i expect that it's from the grave spawning before the explosion happens and then getting destroyed or something.

**Forgotten Graves Version**
1.19.4 - 3.0.4

**To Reproduce**
A list of steps to reproduce your issue, i.e.:
1. die to a creeper with items in your inventory.
2. walk back to your place of death.
3. discover an empty crater without a grave in it and mourn your items.

**Expected behavior**
to not permanently lose my items. every time i die to a creeper.

**Additional context**
[none]

**Screenshots**
![image](https://user-images.githubusercontent.com/95195478/232077045-868c1ab1-f8b5-4ee7-9641-c5aafcb12a45.png)

**Comment by ginsm** [comment]
Thanks for the report and humorous screenshot. That's definitely not supposed to happen!

Graves have a blast resistance of `3600000`.. the same as Bedrock. Definitely not supposed to explode; and they don't even explode if they were placed prior to the explosion. But, here we are, exploding graves!

Either way! I do have a fix I'm testing currently and I'll be pushing it to the affected versions soon (I'll start with v1.19.4, expect it in like ~20 mins or so).

**Comment by ginsm** [comment]
Okay, `1.19.4-v3.0.5` is up on CurseForge and Modrinth now and should fix this. Let me know if there's any further issues, and thanks again for the report! 😁

**Comment by Skidamek** [comment]
Hey, i don't know it was before patch, but now it looks like graves spawn after dying from creeper but the grave is empty. I mean it is just a block that you can craft.
![image](https://user-images.githubusercontent.com/67871298/232565297-539ce0d2-aec6-4a99-9cfd-ea159cee5afe.png)

**Comment by ginsm** [comment]
That's strange. When I test it, it spawns the grave properly:

![image](https://user-images.githubusercontent.com/52685959/232573741-66761b8b-1948-4fec-905b-793d2f8a0988.png)

Which version are you using? And what other mods are you using? :thinking:

**Comment by Skidamek** [comment]
Never mind, it is actually incompatibility between my mod called better explosions. I am sure i can fix it on my side just by excluding graves from interacting with it. But i am curious when this mod creates the grave? Could you send code snippet?

**Comment by ginsm** [comment]
Sure, here's where it first starts to generate the grave:

https://github.com/ginsm/forgotten-graves/blob/main/src/main/java/me/mgin/graves/mixin/PlayerEntityMixin.java

**Comment by Skidamek** [comment]
Got it working (really badly but works, i need to figure out how to save block entities and their inventories). Thanks tho!

**Comment by ginsm** [comment]
I'm working at the moment but if you don't have that figured out by tomorrow I could help out with it; my discord is Syh#9864.

I'll probably take a look tomorrow and see if I can't move when it generates to a point in which explosions won't affect it.. but I'm not quite sure.

Either way, I'm going to re-close this issue!
