### ISSUE TITLE
[BUG] CUSTOM Grave XP Setting Granting 100% XP (like ALL), rather than using the vanilla formula up to the specified cap

### ISSUE THREAD

**Issue by Rebel459** [ginsm/forgotten-graves#67]
See title. Setting the XP setting to CUSTOM grants 100% XP to the cap, rather than using the vanilla formula to a custom cap as specified on the Modrinth page

**Comment by ginsm** [comment]
Thanks for the heads up! I actually changed the functionality a while back and forgot to update the Wiki. I'll go ahead and update that now.

Once I'm finished wrapping up #53 I'll probably revisit the XP setting and add a couple options for it (and make things clearer). If you have any suggestions that you'd like to see, like a particular option for handling XP, feel free to let me know!

**Comment by Rebel459** [comment]
No worries, appreciate the support. I would definitely like to see a return of the old system as the option (7xlevel to cap) or a set % (which would be ideal), as while I love this mod, I can’t include it in my modpack without some further XP configuration. Would be great to be able to have it give you a % of your xp or use the vanilla formula uncapped, though an adjustable percentage would be preferable.

**Comment by ginsm** [comment]
Yup, I was thinking a percentage based one will be good as well. I'm going to try and get #53 done this weekend and then I'll look into sprucing up the XP settings. What version are you on?

**Comment by Rebel459** [comment]
Currently on Fabric 1.19.2 for the foreseeable future. Thanks again for the communication, I greatly appreciate it
