### ISSUE TITLE
dying at world hight crashes server/client

### ISSUE THREAD

**Issue by S0apyy** [ginsm/forgotten-graves#80]
Dying at world height crashes the server

**Forgotten Graves Version**
1.20.1 3.1.0

**To Reproduce**
1. enter server with the mod installed
2. build a platform at world height
3. die

**Expected behavior**
To not crash the server or try to spawn a grave where it cant

**Additional context**
This has happened a lot of times where a grave spawns somewhere where it can't and then proceeds to crash the server, due to either a grave trying to spawn in another grave or trying to spawn at world height. i would like the mod to check for this so it can't happen under any circumstance. after the server crashes there is also no log of any grave being tried to be spawned (no trace of a new grave in the /graves list command) and players just lose their items without any way to get it back.

**Comment by ginsm** [comment]
Thanks for the report; I'll look into this -- the code already checks if it can spawn and iterates to find a suitable position if it cannot so this definitely shouldn't be happening. 🤔

**Comment by ginsm** [comment]
I can't seem to replicate this in my test world: [video](https://youtu.be/RkYfQp7cJz8).

1. Is it generating a crash report of any kind (found in the crash-reports folder, same parent folder as the logs folder)?
2. What does your config file look like? Perhaps there's a config option that's causing the issue?
3. Do you have any other mods installed that might be causing a conflict or issue?

**Comment by S0apyy** [comment]
Yeah heres the crash report from the server i run, and this issue could be serverside only
[crash-2023-09-02_14.38.15-server.txt](https://github.com/ginsm/forgotten-graves/files/12504641/crash-2023-09-02_14.38.15-server.txt)

ill also drop my config in here to see if theres anything wrong with that
[forgottengraves.txt](https://github.com/ginsm/forgotten-graves/files/12504642/forgottengraves.txt)

**Comment by S0apyy** [comment]
This was the recent one but just dying at world height also crashes the server

**Comment by S0apyy** [comment]
You could also test this with the modpack i use for my server called nybblecraft if theres any conflict with mods i have installed on it, its on modrinth

**Comment by ginsm** [comment]
Ended up being able to reproduce the bug and fixing it.. super late though as I had stopped playing Minecraft for a while. Thanks again for the report!
