### ISSUE TITLE
[BUG]Regions Unexplored Plant Trap does not drop grave.

### ISSUE THREAD

**Issue by Zunwolf1896** [ginsm/forgotten-graves#83]
**Describe the bug**
If a player is killed by the plant trap from Regions Unexplored, they do not drop a grave and lose all their items. 

**Forgotten Graves Version**
**Forgotten Graves:** 3.2.1
**Regions Unexplored:** 0.5.31

**To Reproduce**
A list of steps to reproduce your issue, i.e.:
1. Have Regions Unexplored and Forgotten Graves in on a 1.20.1 server 
2. Have a player die to the Plant Trap
3. Encounter error.

**Expected behavior**
PLayer to die from the plant and their grave to spawn next to, on top off or in place off the plant. 

**Additional context**
**MC:** 1.20.1
**Fabric API:** 0.90.0
**Regions UNexplored:** 0.5.31
**Forgotten Graves:** 3.2.1
Have also poste this into Regions Unexplored Discord server.

**Comment by Zunwolf1896** [comment]
https://discord.com/channels/1038703414395273276/1165638150824144969 

^^^ The post on the Regions Unexplored Discord.

**Comment by ginsm** [comment]
Thanks for the report, I'll try and get around to checking this out sometime this week to see what might be going on. I'll keep you updated!

**Comment by UHQ-GAMES** [comment]
might be on our side too. the dusktrap eats entities so it mayy be trying to eat the grave? not too sure as i havent tested it yet

**Comment by ginsm** [comment]
Hmm, so I'm testing it right now and it seems that the grave actually ends up breaking the Dusktrap if you die after standing in it for some time.. but if you run into it with 1 heart the grave ends up not spawning at all.

That leads me to believe that maybe it's occurring when the Dusktrap is switching from its open state to closed? Maybe around [here](https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/blob/606d485bc6155860baeab46c110c4966250cd2c6/src/main/java/net/regions_unexplored/world/level/block/plant/dusktrap/BaseDuskTrapBlock.java#L89C15-L89C15)? Just a quick assumption from skimming the code. Like the player dies, the grave spawns, but quickly gets overwritten by the plant's closed state.. something along those lines.

I've been planning on implementing some better spawning rules on my end anywho, where the grave will try and find a better spot to spawn, preferring air or liquids over blocks that don't have a full collision, so I'll try and work on getting that done this week and then it *shouldn't* be an issue.

For now, if you'd like to recover your stuff, you can run `/graves list 1 <playername>` as an operator to get a list of grave backups and click `[R]` on any grave you'd like to retrieve.

**Comment by ginsm** [comment]
Alright, I modified the placement search algorithm so that this shouldn't happen anymore. I've done some testing and from what I can tell this issue should be resolved.

I'm publishing the update to Modrinth and CurseForge currently; it should be available within the next ~10-15 minutes. I'm going to close this now but if the issue persists in v3.2.3 please let me know, thanks! :grin:

**Comment by UHQ-GAMES** [comment]
Thanks for the quick action @ginsm ! i also made a few changes to the Dusktrap block to help as well so it should no longer be and issue period lol
