### ISSUE TITLE
[BUG] Incompatible with Better Totem of Undying

### ISSUE THREAD

**Issue by Answordy** [ginsm/forgotten-graves#84]
When I install this mod into my modpack where several other mods are using cloth config I get this message:
![2023-10-23_22h-53m-48s](https://github.com/CERBON-MODS/CERBONs-Better-Totem-of-Undying-FORGE/assets/82783515/c6a91d28-8cc7-4e1a-b5ba-ab122347730b)

If I remove or add older cloth config version I get this message:
![2023-10-23_22h-54m-21s](https://github.com/CERBON-MODS/CERBONs-Better-Totem-of-Undying-FORGE/assets/82783515/63ed51dc-63ea-4543-93f1-8e883e0f2fd8)

If I remove Better Totem of Undying or Forgotten Graves I get no error and the game loads. Not sure which mod is causing the issue.

**Comment by ginsm** [comment]
Thanks for the report! 

I'm pushing out an update to fix this and it should be on Modrinth and CurseForge within the next ~10-15 minutes.

It'd be appreciated if you could let me know if the update fixes your issue, thanks!
