### ISSUE TITLE
[FEATURE] Compatibility Traveler's backpack mod

### ISSUE THREAD

**Issue by GameBurrow** [ginsm/forgotten-graves#86]
**Is your feature request related to a problem? Please describe.**
> From one of the players in our community:
> ![image](https://github.com/ginsm/forgotten-graves/assets/4341091/2260a8b1-5eca-458b-8bcd-d9af2410ea76)
> The backpack spawned, then the grave spawned overtop, deleting the backpack

**Describe the feature you would like to see.**
As traveler's backpack is only compatible backpack mod with Fabric (I know of), it would be nice if the mod is ompatible with it:
https://modrinth.com/mod/travelersbackpack

**Describe any alternatives you've considered.**
None that I can think of-

**Additional context**

**Comment by ginsm** [comment]
What version of forgotten graves are you on?

**Comment by GameBurrow** [comment]
> Sorry to hear that happened, what version of forgotten graves are you on?

Hey are on the latest release available on modrinth: `filename = "forgottengraves-1.20.1-3.2.4.jar"`

**Comment by ginsm** [comment]
That definitely shouldn't happen then. :thinking: The code is supposed to check if there's anything at the position it's trying to spawn at before spawning.. and if there is, it's supposed to look elsewhere (defaulting to the original position if there's no other space it can spawn). I'll have to test it out and figure out what's going on there. Probably related to #85.

For now, do you happen to have Trinkets in your modpack? If so, you could modify `travelersbackpack.json5`'s `backpackSettings` to something like this:
```json5
"backpackSettings": {
	"enableTierUpgrades": true,
	"disableCrafting": false,
	// Enables wearing backpack directly from ground
	"enableBackpackBlockQuickEquip": true,
	// Backpack immune to any damage source (lava, fire), can't be destroyed, never disappears as floating item
	"invulnerableBackpack": true,
	// List of items that can be put in tool slots (Use registry names, for example: minecraft:apple)
	"toolSlotsAcceptableItems": [],
	// List of items that can't be put in backpack inventory (Use registry names, for example: minecraft:apple)
	"blacklistedItems": [],
	"allowShulkerBoxes": false,
	"tanksCapacity": [
		162000,
		243000,
		324000,
		405000,
		486000
	],
	// Prevents backpack disappearing in void
	"voidProtection": false,
	// Places backpack at place where player died
	"backpackDeathPlace": false,
	// Places backpack at place where player died, replacing all blocks that are breakable and do not have inventory (backpackDeathPlace must be true in order to work)
	"backpackForceDeathPlace": false,
	"enableSleepingBagSpawnPoint": false,
	/* If true, backpack can only be worn by placing it in curios 'Back' slot
	WARNING - Remember to TAKE OFF BACKPACK BEFORE enabling or disabling this integration!! - if not you'll lose your backpack
	*/
	"trinketsIntegration": true
},
```
That'll cause the backpack to store directly in the grave (but requires Trinkets).

**Comment by GameBurrow** [comment]
Yes, we have trinkets indeed. Imagine the settings that are the important ones are:
backpackDeathPlace - `false`
backpackForceDeathPlace - `false`
trinketsIntegration - `true`

Is that correct?

**Comment by ginsm** [comment]
Yup, that's correct. Once I figure out what's going on and fix it I'll let you know in case you want to switch back to non-Trinket integration.

**Comment by GameBurrow** [comment]
I actually prefer the trinkets integration, didn't look at the config so didn't know we didn't have it enabled. Thanks for that :)

**Comment by ginsm** [comment]
`v3.2.5` should fix this issue (for anyone who prefers non-trinket integration) so I'm going to close this issue for now.

Thanks again for the report! :grin:
