### ISSUE TITLE
[BUG] Renaming doesn't work properly

### ISSUE THREAD

**Issue by mpustovoi** [ginsm/forgotten-graves#87]
**Describe the bug**
After renaming the grave on the anvil, instead of the name, the entire text format is displayed on it

**Forgotten Graves Version**
v.3.2.4 for Fabric 1.20.1

**To Reproduce**
On Fabric 1.20.1
1. Install Forgotten Graves v.3.2.4.
2. Install Easy Anvils v.8.0.1 (maybe it's a compatibility issue with that mod)
3. Install Fixed Anvil Repair Cost v.3.2 (as far as I know, this is the second mod that somehow affects the anvil)
4. Rename the grave of any state of erosion with the anvil.
5. Place it and see the full text format instead of the actual name.

**Expected behavior**
A custom name should be displayed on the grave.

**Additional context**

I don't know how long this problem has existed. My friend just decided to try renaming the grave just now and it failed.

**Screenshots**
![image](https://github.com/ginsm/forgotten-graves/assets/92390626/92b904cf-c466-4fcc-8e28-d29a15275636)
![image](https://github.com/ginsm/forgotten-graves/assets/92390626/a82f54ef-0a74-4fdf-883c-6e8d942811ce)

**Logs**
I didn't notice any errors in the log, but here it's anyway:
https://gist.github.com/mpustovoi/3b1cb63ed576dc108a9bc9df801689b4

**Comment by ginsm** [comment]
Hey there, thanks for the report. I have an idea what it might be but I'll need to test a bit before I can actually fix the issue.

**Comment by ginsm** [comment]
This has been fixed in `1.20.1-3.2.6` (should be on Modrinth and CurseForge soon) so I'm going to close this issue.

Versions `1.20`, `1.20.2`, and `1.20.3` can expect this fix within the next few days as well.
