### ISSUE TITLE
[BUG] Create Drill deleting NBT data and therefore item

### ISSUE THREAD

**Issue by Paradox9153** [ginsm/forgotten-graves#88]
This is a more niche bug but when a drill breaks a gravestone it losses all the items it was storing (this might be with any non-player breakage but im not sure)

Ver. 1.20.1-3.2.5

1. Die 
2. Spawn grave
3. Have drills (from create mod) break grave
4. lose item

1. drop items on to ground 
2. store item into moving storages if drills are connected to moving object 

I would like to also mention that it states that the graves exists at coordinates and that its unopened but when going to said coordinates there is no grave

**Comment by PolyframeX** [comment]
This issue can also be encountered if you disable the breaking mode, therefore since the nbt data is missing. the grave is just permanently stuck there forever.

**Comment by ginsm** [comment]
Thanks for the heads up, @PolyframeX. Been a bit inactive, I'm not really playing Minecraft much these days and been busy with other things, but I'll see what I can do sometime soon™️. Maybe later this week.. I want to get around to updating it to 1.20.4 before I work on anything else though.
