### ISSUE TITLE
[Feature Request] Ability to disable Graves (Effect/Player Based) 

### ISSUE THREAD

**Issue by A5ho9999** [ginsm/forgotten-graves#89]
**Is your feature request related to a problem? Please describe.**
Not a problem, pure selfish request.

**Describe the feature you would like to see.**
Firstly this is purely a pretty selfish request but would like the ability to disable a grave spawning for certain players/a player with a specific effect. Taking Xaero's Minimap as an example they add effects to disable certain things from entities to the entire map itself.

**Additional context**
We use the mod on our server where we are building a little minigame that involves the players possibly dying but the graves would clutter up the map (they aren't meant to keep their obtained items from with-in the minigame if they die). So having the ability to turn off the graves for the player during the minigame without affecting the whole server would be amazing.

**Comment by ginsm** [comment]
Hey there, thanks for the request! If I'm understanding correctly, you can accomplish something like that as-is depending on which version you're using (though not through effects). Here's a quick rundown of how you can do so:

## Server-side
If you run the following command as an operator in-game, it'll configure the server to allow players to enable/disable their own grave spawning:

`/graves server config set clientOptions add graves`

## Client-side
After setting that, the different players can their disable their own graves either via Mod Menu or a command:

`/graves config set graves <false|true>`

## Command Blocks
If you want, you could use command blocks to enable/disable graves for players within a specific radius of the command block and just have your players press it (or step on it) when they go into the area and leave the area. Here are the commands you'd need to use for the command blocks:

**Enable Graves**
`execute as @e[distance=..4] run graves config set graves true`

**Disable Graves**
`/execute as @e[distance=..4] run graves config set graves false`

----

I hope this helps! :grin: Let me know if you have any questions.

As for an effect that disables grave spawning, I probably won't rush to add it but it is an interesting idea so I might add it eventually!

**Comment by A5ho9999** [comment]
I'll keep these in mind thank you, using commands isn't the best option as they require a lot of explaining for the player and people will most likely forget to re-enable the graves afterwards, the command block could work, we'd just have to find a good way to re-enable it after the player death. The effect would still be the most ideal way so I do hope it gets added eventually.

**Comment by ginsm** [comment]
I've went ahead and added an effect to disable graves (the ID for the effect is `forgottengraves:disablegraves`). To make it apply in a radius within an area, you can hook up a command block with a clock and the following command (adjust the distance and duration as desired):

`/effect give @a[distance=..30] forgottengraves:disablegraves 10`

I know it took me a while to add this but it will be part of the next update. I'm going to close this issue now, thanks again for the request!
