### ISSUE TITLE
[BUG] If Mod is active, creeper or TNT did not make any block damage

### ISSUE THREAD

**Issue by Cape-City** [ginsm/forgotten-graves#92]
**Describe the bug**
Mod active: No block damage due creeper or TNT anymore
Mod inactive: normal behavior

**Forgotten Graves Version**
forgottengraves-1.20.4-3.2.6.jar
MC 1.20.4
fabric-api-0.96.11+1.20.4.jar
Fabric 0.15.9

**To Reproduce**
A list of steps to reproduce your issue, i.e.:
1. Create clean profile with only this mod active
2. Create new world
3. Spawn creeper and let them explode

**Expected behavior**
Normal Blockdamage

https://mclo.gs/CyWUDVi

**Comment by ginsm** [comment]
This should be affecting both `1.20.3` and `1.20.4`. I have an idea of how to fix it, but I'll need to play around with the code when I get home from work.

I'll see if I can't get an update out later tonight. Thanks for taking the time to make a report!

**Comment by ginsm** [comment]
Alright, I'm pushing out a release for `1.20.4` right now that fixes this bug (`v3.2.7`); let me know if you run into any more issues & thanks again for the report!
