### ISSUE TITLE
[BUG] Incompatibility with "Rats Mischief 2.0"

### ISSUE THREAD

**Issue by Simsz** [ginsm/forgotten-graves#95]
**Describe the bug**
RAT's Mischief lets you take over "Spy Rats" and control them. Whenever you stop taking over the rat, a gravestone will spawn at the rats location

**Forgotten Graves Version**
v1.19.2-3.2.2 Fabric (on quilt)

**To Reproduce**
Use both mods.
Craft a spy rat (eye of ender, rabbit hide, tamed rat)
![image](https://github.com/ginsm/forgotten-graves/assets/12779829/8330897c-65d7-455f-88f4-8ad484257a70)
You can tame a rat by feeding it then shift+right click to pick it up and use it to craft

Use the "Rat Master Mirror" to control the spy rat

Stop controlling the spy rat and a gravestone will spawn.

**Expected behavior**
No Gravestone should spawn

**Comment by ginsm** [comment]
Thanks for the report! I've resolved the issue and will be pushing out a patched 1.19.2 version shortly.
