### ISSUE TITLE
[BUG] Supplementaries Bomb and Create Drill just deletes the Items in the grave and or drops the grave as an item

### ISSUE THREAD

**Issue by NextRaven10** [ginsm/forgotten-graves#96]
**Describe the bug**
Supplementaries Bomb and Create Drill just deletes the Items in the grave and or drops the grave as an item

**Forgotten Graves Version**
Forgotten Graves 1.20.1-3.2.6

**To Reproduce**
A list of steps to reproduce your issue, i.e.:
1. Throw a Bomb from Supplementaries at yourself
2. Die because of it
3. See your Grave and your Items beeing destroyed

**Expected behavior**
That the bomb wouldn´t be able to destroy the grave or that it replaces itself or that all the items drop or that the grave with all the items inside drops

**Additional context**
-

**Screenshots**
![2024-05-20_19 21 55](https://github.com/ginsm/forgotten-graves/assets/73491206/769345fd-7faf-40f8-9e75-354e63ed0da6)
![2024-05-20_19 21 57](https://github.com/ginsm/forgotten-graves/assets/73491206/3146292d-ffc1-4875-a54a-79e0bcc2cb75)
![2024-05-20_19 22 27](https://github.com/ginsm/forgotten-graves/assets/73491206/54140cdd-841d-4a6d-af0f-48517a5a079a)

**Comment by ginsm** [comment]
Hey, thanks for the report!

To stop the bombs from destroying the grave when they kill you, you can change `Break Blocks` to `NONE` for both regular bombs and blue bombs. The settings for the bombs are found in `supplementaries-common.json` under the `tools` section. I'll look into fixing it on my side as well but this should work for now.

Issue #88 has made me aware of the Create bug already but currently my main focus for this mod is #93.. so it likely won't be fixed until that's done.

**Comment by ginsm** [comment]
Commit 32125d3 fixes the Create drill issue. I'm going to try and fix the Supplementaries bomb issue this week and get the update pushed out in `3.2.10`.

**Comment by ginsm** [comment]
Alright, commit a22c65f should resolve this issue. Just gotta do some testing for `3.2.10` and then I'll release it. Closing this for now.
